version: '3.4'
services:
  # jaeger:
  #  image: jaegertracing/all-in-one:1.49
  redis:
   image: redis:7.0
  rabbitmq:
   image: rabbitmq:3.12.2-management
  # elasticsearch:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1  
  # kibana:
  #  image: docker.elastic.co/kibana/kibana:8.8.1 
  otel-collector:
   image: otel/opentelemetry-collector-contrib:0.85.0


