version: '3.4'
services:
  metric.api:
   image: metric.api.image
   build:
    context: .
    dockerfile: Metric.API/Dockerfile
  prometheus:
   image: prom/prometheus:v2.37.9
   volumes: 
    - ./prometheus.yml:/etc/prometheus/prometheus.yml


